### ISSUE TITLE
HOWTO: Cancellable task

### ISSUE THREAD

**Issue by alunux** [albfan/gtask-example#1]
Hi @albfan, thanks for the great example about GTask. Could you add an example how to cancel unfinished task and start new task when the button is pressed again? Thank you! :)

**Comment by albfan** [comment]
Sure I will do in a while

**Comment by albfan** [comment]
Done. Hope you find it useful.

I have added a cancel button and linked a callback where I pass the cancellable as data. 

Whenever I press it, the object is marked as cancelled and you can check that directly on while loop, to stop job

Close this issue if that's what you're looking for

**Comment by albfan** [comment]
This was mostly done with Builder, https://builder.readthedocs.io/en/latest/ give it a try

**Comment by alunux** [comment]
It works as expected, thank you!
